export const SET_ME_SHORTCUTS_LOADING = '[PROFILE] SET ME SHORTCUTS LOADING';
export const SET_ME_SHORTCUTS = '[PROFILE] SET ME SHORTCUTS';
export const RESET_ME_SHORTCUTS = '[PROFILE] RESET ME SHORTCUTS';
